TIEBA_CRAWLER_DEFAULTS = {
    "tieba_name": "示例高校",
    "source": "latest",
    "max_threads": 200,
    "headless": False,
    "threads_per_page_guess": 20,
    "max_list_pages": 10,
    "list_page_pn_step": 50,
    "manual_verify_timeout": 180,
    "page_load_timeout": 60000,
    "post_load_timeout": 20000,
    "scroll_times": 8,
    "scroll_step": 1000,
    "scroll_sleep": 0.5,
    "list_page_sleep": 3,
    "list_settle_sleep": 1,
    "post_page_sleep": 1.5,
    "between_posts_sleep": 0.8,
    "stop_on_duplicate_streak": 8,
    "debug_response_chars": 50000,
    "thread_response_chars": 500000,
}
